---
- name: Provision nodejs dev box
  hosts: all
  become: yes

  tasks:
    - name: enable epel repo
      yum:
        name: epel-release
        state: installed

    - name: add custom repo for ruby
      yum_repository:
        name: fnrpms
        description: s3 bucket full of rpms
        baseurl: "http://fnrpms.s3-website-us-east-1.amazonaws.com/$releasever/$basearch"
        gpgcheck: no
        enabled: yes

    - name: install nodejs and dependencies
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - nodejs
        - npm
        - docker
        - python-setuptools

    - name: create the docker group
      group:
        name: docker
        state: present

    - name: add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: restart docker
      service:
        name: docker
        state: restarted
